---
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, loggers
spring:
  docker:
    compose:
      enabled: false
server:
  port: 8085

value:
  name: ${NAME}
